### ISSUE TITLE
Test script does not exit correctly

### ISSUE THREAD

**Issue by ustims** [ustims/DartORM#18]
When you directly run `dart test/mysql_integration_test.dart`, the process does not exit. 
I suppose it's because the connection to database is not closed when test ends.
However, `connection.close()` could not be placed to `tearDown` because it will run after each of the testcases.

@kevmoo Do you know any way to run something after all tests? Maybe we could wrap everything in one group()?

**Comment by kevmoo** [comment]
That's being worked on - https://github.com/dart-lang/test/issues/18

**Comment by kevmoo** [comment]
We should be able to run on this now.

**Comment by ustims** [comment]
Nice, we have coverage badge now 😎
