### ISSUE TITLE
Build failing in CI system

### ISSUE THREAD

**Issue by sethladd** [ustims/DartORM#3]
Just noticed the drone.io build is failing. Someone was asking about an ORM solution for Dart, and I found this package. But, will wait to share until we see the build succeeding again. First impressions and all that :)

Thanks for working on this! Lots of people ask about what ORM options there are for Dart.

**Comment by ustims** [comment]
Hi, Seth! Thanks for your feedback. You were the one who acquainted me with Dart through a series of video "Darth Tips" so I appreciate it :)

I've fixed the tests so builds are green now.

**Comment by sethladd** [comment]
Thanks for the fix! :)
